package dataStructure.javaStrings.level1;

import java.util.Scanner;

public class IllegalArgumentExceptionDemo {

    // Method to generate an invalid substring operation
    public static void generateException(String text) {

        // Set the start index greater than the end index
        int startIndex = text.length();
        int endIndex = 0;

        // Attempt to create an invalid substring
        text.substring(startIndex, endIndex);
    }

    // Method to handle the runtime exception
    public static void handleException(String text) {

        try {

            // Set the start index greater than the end index
            int startIndex = text.length();
            int endIndex = 0;

            // Attempt to create an invalid substring
            text.substring(startIndex, endIndex);

        } catch (IllegalArgumentException exception) {

            // Handle IllegalArgumentException
            System.out.println(
                    "IllegalArgumentException handled."
            );

        } catch (RuntimeException exception) {

            // Handle the actual runtime exception from substring()
            System.out.println(
                    "RuntimeException handled: "
                            + exception.getClass().getSimpleName()
            );
        }
    }

    public static void main(String[] args) {

        // Create Scanner object for user input
        Scanner input = new Scanner(System.in);

        // Take the string as input
        System.out.print("Enter a string: ");
        String text = input.nextLine();

        try {

            // Call the method that generates the invalid operation
            generateException(text);

        } catch (RuntimeException exception) {

            // Catch the runtime exception generated by substring()
            System.out.println(
                    "Invalid substring operation generated: "
                            + exception.getClass().getSimpleName()
            );
        }

        // Call the method that handles the exception
        handleException(text);

        // Close Scanner
        input.close();
    }
}
